:Exercise
A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

Given that A is an ndarray object, many functionalities in numpy could be accessed by:
Make sure to explain each line of codes that you have created.
Using a property of the ndarray object
e.g. A.shape
Using a method of the ndarray object
e.g. A.max()
Using a numpy function and passing an ndarray
e.g. np.max(A)
B. Create a 5x5 integer-array filled with ones.

Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.
C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

A.

In [ ]:
import numpy as np  # Importing numpy library

# Creating a nested Python list with values from 1 to 100
nested_list = [[i for i in range(1, 101)]]

# Converting the nested list into a numpy ndarray object
A = np.array(nested_list)

# Printing the shape of the ndarray object
print("Shape of A:", A.shape)

# Finding the maximum value in the ndarray object using a method
print("Maximum value in A:", A.max())

# Using a numpy function to find the maximum value in A
print("Maximum value in A (using np.max):", np.max(A))


Shape of A: (1, 100)
Maximum value in A: 100
Maximum value in A (using np.max): 100


B.

In [ ]:
# Creating a 5x5 integer array filled with ones
ones_array = np.ones((5, 5), dtype=int)

# Printing the shape, size, and number of dimensions of the array
print("Shape of ones_array:", ones_array.shape)
print("Size of ones_array:", ones_array.size)
print("Number of dimensions of ones_array:", ones_array.ndim)


Shape of ones_array: (5, 5)
Size of ones_array: 25
Number of dimensions of ones_array: 2


C.

In [ ]:
# Creating an array of values from -5 to 5
values_array = np.arange(-5, 6)

# Multiplying each value in the array by 2
result_array = values_array * 2

# Printing the resulting array
print("Resulting array:", result_array)


Resulting array: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


Exercise
A. Choose the values from the range of numbers 1 to 100.

Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
Explain what is the result briefly by writing a comment before the code.
Multiply the resulting array with 3. Print the result.

In [ ]:
# Creating an array with 30 values within the range of numbers 1 to 100,
# with an increment of 2
array = np.arange(1, 61, 2)

# Multiplying each value in the array by 3
result = array * 3

# Printing the result
print("Resulting array:", result)


Resulting array: [  3   9  15  21  27  33  39  45  51  57  63  69  75  81  87  93  99 105
 111 117 123 129 135 141 147 153 159 165 171 177]


Exercise
A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.

Get the dimensions, shape, and size.
Explain what is the result briefly by writing a comment before the code.
B. Get the maximum number for each dimensions and display it.

Explain what is the result briefly by writing a comment before the code.
C. Multipy each array with 4. What is its result? * Write a brief explanation on the multiplication process.

In [2]:
# Creating a four-dimensional array of random integers in the interval [0, 12]
import numpy as np
four_dim_array = np.random.randint(0, 13, size=(3, 4, 5, 6))

# Printing the array
print("Four-dimensional array:\n", four_dim_array)

# Getting dimensions, shape, and size
print("Dimensions:", four_dim_array.ndim)
print("Shape:", four_dim_array.shape)
print("Size:", four_dim_array.size)

# Getting the maximum number for each dimension and displaying it
max_values = [four_dim_array[:, :, :, i].max() for i in range(four_dim_array.shape[3])]
print("Maximum number for each dimension:", max_values)

# Multiplying each array element by 4
multiplied_array = four_dim_array * 4

# Printing the result
print("Result after multiplying each array element by 4:\n", multiplied_array)

#Every integer value in the four-dimensional array is multiplied by four when each array element is multiplied by four.
#Throughout the entire array, this procedure is applied element by element.
#Each element in the resultant array is multiplied by four, and it has the same shape as the original array.


Four-dimensional array:
 [[[[11 11 12  2  2  8]
   [ 6  5  9 11  2  3]
   [ 2  4  6 12  4 10]
   [ 6  6  4  2 12  4]
   [11  2  0  4  5  6]]

  [[ 7  1  6  8  7  3]
   [ 7 10  9  2  1  9]
   [ 4  9 11 11  3 10]
   [ 9  2  1  5 10  0]
   [ 6  2 10 11  7 12]]

  [[ 5  1  1  1  3  7]
   [ 8 12  4 12  2  5]
   [ 1  4  0 12  4  2]
   [ 6  9  1  2  4  4]
   [ 8  1  7 11  2  3]]

  [[ 4  9  8  8 11  4]
   [ 6 10 12 12  3  9]
   [ 2 12  4 11 11  9]
   [ 1  0  3  9  4  6]
   [10  4  2  0  0 10]]]


 [[[ 7 12  3  4  7  2]
   [ 0  3  6  2  9 12]
   [ 0 12  3  2 11 10]
   [ 7  7  9  3  5 11]
   [ 5  0  9  1  6  0]]

  [[ 9  9 11 12  3 11]
   [12  4 11  8  0  9]
   [12 11  4  5  6  2]
   [ 7  6 10 10  5  5]
   [10  3  3  3  1 11]]

  [[12  9 12  6  3  6]
   [ 4  5  5 10  0  5]
   [12  3  1  0  9  7]
   [12 11  5  0  2 11]
   [ 1  9  5  9  4 10]]

  [[ 7  7 11 12  7  5]
   [ 1 12 11  1 10  4]
   [12  5  1  5  1 12]
   [ 3  2  6  2  4  1]
   [12  3  7  1  4 10]]]


 [[[ 8  6  9  9  2  1]
   [11  4 12